### ISSUE TITLE
Filtering Date type columns

### ISSUE THREAD

**Issue by john-parker57** [oliversturm/devextreme-query-mongodb#40] opened 2022-10-06 09:04 UTC
Hello,
I'm trying to filter a devexpress grid with Date type columns against mongo Date type properties but empty results are returned.

Example of date stored in mongo: "lastUpdated" : ISODate("2022-06-15T23:13:04.000Z")

Example of loadoptions supplied to devextreme-query-mongodb which we pass straight to the query method:
![image](https://user-images.githubusercontent.com/110240328/194270321-96e635f6-8147-4ce3-bb5c-d17291ffc23c.png)

Do you have any pointers please on what I might be missing?

Thanks,
John

**Comment by oliversturm** [comment] 2022-10-06 10:17
I have just added [this test](https://github.com/oliversturm/devextreme-query-mongodb/blob/8fc5620dd8ad904dae96b451503c72f0ba0967ce/src/index.test.js#L2214-L2231) to check that filtering works correctly for a scenario very similar to yours. Unfortunately I can't reproduce your problem on that basis, so the obvious question would be whether your additional criterion for the `schemaId` perhaps causes the result to be empty.

Otherwise, perhaps you can give the test code a go and see what exactly the difference is compared to your own data or implementation.

**Comment by john-parker57** [comment] 2022-10-06 10:52
Thanks for quick reply.

I've just noticed if I change the how the dates are stored in mongo from date objects to strings then the expected results are returned.

e.g. change:
"lastUpdated" : ISODate("2022-06-15T23:13:04.000Z")
to:
"lastUpdated" : "2022-06-15T23:13:04.000Z"

**Comment by oliversturm** [comment] 2022-10-06 12:32
That is interesting, but it's something I specifically checked when I did the test. I found that the test database contains all dates in ISODate format, and the test works correctly nevertheless.

Perhaps this is nevertheless part of the explanation. You can see in the test code how the data is encoded when it is stored, and how the query is constructed. Perhaps this is somehow different from the way you do it? I imagine it's possible that the browser debugger (i.e. your screenshot above) or some `console.log` output does not show the right details, that's why I would compare the way the code is written to be sure.

Edit: additionally, if you use strings you will lose the features that extract part of the date information (support for Pivot Grid, mainly), and I don't think comparison will be as performant on the string basis (even though it should be reliable since the string is stored in the correct "order" to allow string comparisons to return correct results).

**Comment by john-parker57** [comment] 2022-10-06 15:15
I can see one difference in that we take the filter expression provided by the devexpress grid as is - containing iso date strings - and use that in the query method.

below is taken from VS Code debugger in our backend just before it makes the query call:
![image](https://user-images.githubusercontent.com/110240328/194350375-0c81f9ac-894e-47b0-9b81-6c4df6ac91c8.png)

In your test you supply new Date objects for the filter values instead of ISO date strings:
![image](https://user-images.githubusercontent.com/110240328/194350556-a72e29a7-860e-4f1b-a5b5-49d08f1c3fb3.png)


I've tried changing our date strings to Date objects before calling query:
![image](https://user-images.githubusercontent.com/110240328/194367723-3f3c703b-cd47-41c8-ab4d-ca9e1d131302.png)
![image](https://user-images.githubusercontent.com/110240328/194368073-defa0c7e-a86c-4344-941b-c419296081b5.png)

and the expected results are now returned.


**Is this something we should do - i.e. replace date strings with Date objects in the filter expression supplied to the query if we store date type in the database?**

**Comment by oliversturm** [comment] 2022-10-07 07:29
Good work finding this out. I might have thought of that...

There's a mechanism in the library to accept a schema ([info here](https://github.com/oliversturm/devextreme-query-mongodb/wiki/OptionsAPI#using-a-schema)), and this has support for a `datetime` type. [This test](https://github.com/oliversturm/devextreme-query-mongodb/blob/8fc5620dd8ad904dae96b451503c72f0ba0967ce/src/options.test.js#L987-L1005) shows how a schema can be used to auto-convert a date/time value supplied as a string in a filter criterion into an actual `Date` object. 

I think this should work for you, only I don't recall whether we have support for both these schema variants:

```js
{
  'data.header.statementDate': 'datetime'
}
```

```js
{
  data: {
    header: {
      statementDate: 'datetime'
    }
  }
}
```

I suggest you start with the first syntax, I think that's the one supported by the mechanism.

**Comment by john-parker57** [comment] 2022-10-07 10:06
Thanks, I tried both and the first syntax works.

**Comment by oliversturm** [comment] 2022-10-07 10:22
Good news. I'll close this for now, feel free to reopen in case you have more trouble.

**Closed as completed by oliversturm** 2022-10-07 10:22 UTC

**Comment by john-parker57** [comment] 2022-10-07 12:13
Hi,

Just checking that the definitive list of schema field mapping types you can supply to OptionsAPI are  "int", "float", "datetime" and "bool"?

I cant find "datetime" mentioned on https://github.com/oliversturm/devextreme-query-mongodb/wiki/OptionsAPI so just wanted to be sure.

**Comment by oliversturm** [comment] 2022-10-07 13:07
That's correct, from [the implementation](https://github.com/oliversturm/devextreme-query-mongodb/blob/8fc5620dd8ad904dae96b451503c72f0ba0967ce/src/options.js#L32-L39):

```js
function fixValue(type, value) {
    return {
      int: parseInt,
      float: parseFloat,
      datetime: (v) => new Date(v),
      bool: asBool,
    }[type](value);
}
```

I'll update the documentation to list the names correctly. Thanks for pointing that out.
